language: python
matrix:
  include:
    - python: 2.7
      env: PLONE_VERSION=5
    - python: 3.7
      env: PLONE_VERSION=5
install:
  - mkdir -p buildout-cache/downloads
  - pip install -r requirements.txt
  - buildout -c travis-$PLONE_VERSION.x.cfg
script:
  - bin/test
#after_success:
#  - bin/coverage-report
#  - pip install -q coveralls
#  - coveralls
